-- Batch 4: 100 additional winning dropshipping products, bringing the
-- catalog to 250. Every image_url was sourced from a live Unsplash search
-- for that specific product and cross-checked against batches 1-3 (plus
-- the image_updates.sql corrections) to avoid any repeats. created_at is
-- spread across the last 60 days (relative to whenever this runs) so the
-- "New Arrivals" tab shows real variety instead of a single timestamp.

INSERT INTO products (title, description, image_url, niche, supplier_url, demand_score, trend_label, is_featured, created_at) VALUES

-- Home Decor (15)
('Cloud Dimmable Table Lamp', 'Soft-glow dimmable table lamp with a cloud-shaped silhouette — a favorite in "cozy bedroom" and study-space content thanks to its warm, nursery-to-adult-room crossover appeal. Touch-dimming makes for an easy one-tap demo video.', 'https://images.unsplash.com/photo-1570974802254-4b0ad1a755f5?w=400', 'Home Decor', 'https://www.aliexpress.com', 82, 'Trending', true, NOW() - INTERVAL '4 days'),
('Industrial Pipe Wall Shelf', 'Black metal pipe-and-wood wall shelf that anchors the industrial-loft aesthetic trending across apartment-makeover content. Simple mounting hardware makes for an easy before/after demo video.', 'https://images.unsplash.com/photo-1608610025929-c9f376a28c04?w=400', 'Home Decor', 'https://www.aliexpress.com', 74, 'Rising', true, NOW() - INTERVAL '52 days'),
('Abstract Terrazzo Vase', 'Speckled terrazzo-pattern ceramic vase that rides the sustained maximalist-decor trend — a strong "shelf styling" impulse buy with broad appeal across boho and modern interiors alike.', 'https://images.unsplash.com/photo-1526198049595-f32cde2a219d?w=400', 'Home Decor', 'https://www.aliexpress.com', 76, 'Rising', true, NOW() - INTERVAL '31 days'),
('Woven Seagrass Storage Baskets', 'Set of stackable seagrass storage baskets that double as decor — a reliable "organize with me" content staple with genuine daily-use utility across every room in the house.', 'https://images.unsplash.com/photo-1455669175216-9017c9b02fc6?w=400', 'Home Decor', 'https://www.aliexpress.com', 79, 'Trending', true, NOW() - INTERVAL '17 days'),
('Marble-Look Coaster Set', 'Faux-marble coaster set that upgrades a coffee table for a fraction of real stone pricing — low shipping weight, high perceived value, and a natural bundle upsell with placemats.', 'https://images.unsplash.com/photo-1780241626535-9787b7b1a842?w=400', 'Home Decor', 'https://www.aliexpress.com', 71, 'Rising', true, NOW() - INTERVAL '45 days'),
('Wall-Mounted Jewelry Organizer Mirror', 'Mirrored jewelry organizer that mounts flush on a wall or door — a genuinely useful "get ready with me" product with strong tutorial-style short-form video potential.', 'https://images.unsplash.com/photo-1719861553600-867d1f01ac03?w=400', 'Home Decor', 'https://www.aliexpress.com', 83, 'Trending', true, NOW() - INTERVAL '9 days'),
('Rattan Reed Diffuser Set', 'Reed diffuser with a rattan-topped glass bottle that looks like a design piece, not an air freshener — strong repeat-purchase economics once a customer buys their first refill oil.', 'https://images.unsplash.com/photo-1750429431308-96eb0e8b6f6f?w=400', 'Home Decor', 'https://www.aliexpress.com', 80, 'Trending', true, NOW() - INTERVAL '23 days'),
('Modern Arc Floor Lamp', 'Sweeping arc floor lamp that anchors a living room seating area without needing an outlet nearby — a higher-AOV lighting SKU with strong "room glow-up" ad-angle potential.', 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?w=400', 'Home Decor', 'https://www.aliexpress.com', 75, 'Rising', true, NOW() - INTERVAL '38 days'),
('Textured Boucle Throw Blanket', 'Chunky boucle-knit throw blanket riding the sustained "cozy minimalism" home trend — a top-performing gifting SKU every fall and winter with broad, non-niche appeal.', 'https://images.unsplash.com/photo-1734553529922-bc020a21643b?w=400', 'Home Decor', 'https://www.aliexpress.com', 89, 'Hot', true, NOW() - INTERVAL '2 days'),
('Wooden Bead Garland Decor', 'Hand-strung wooden bead garland for shelves and mantels — a low-cost, high-margin styling accent with strong repeat interest from the boho and farmhouse decor niches.', 'https://images.unsplash.com/photo-1646910084432-71d0fef4085e?w=400', 'Home Decor', 'https://www.aliexpress.com', 73, 'Rising', true, NOW() - INTERVAL '56 days'),
('Acrylic Floating Bookshelf', 'Nearly invisible acrylic floating shelf that makes books and decor look like they''re suspended on the wall — a strong "how did they do that" ad angle with genuine wow-factor.', 'https://images.unsplash.com/photo-1652218484720-cd53e15ce7a6?w=400', 'Home Decor', 'https://www.aliexpress.com', 77, 'Rising', true, NOW() - INTERVAL '14 days'),
('Rechargeable Cordless Table Lamp', 'Battery-powered cordless table lamp that moves anywhere — patio, bedside, dinner table — without an outlet. A strong "ambiance anywhere" angle for the outdoor-entertaining audience.', 'https://images.unsplash.com/photo-1573676386604-78f8ed228e2b?w=400', 'Home Decor', 'https://www.aliexpress.com', 81, 'Trending', true, NOW() - INTERVAL '6 days'),
('Linen Tassel Curtain Tiebacks', 'Woven linen curtain tiebacks with a tasseled finish — a cheap-to-ship accent that instantly elevates plain curtains, popular in the "small budget, big impact" decor content niche.', 'https://images.unsplash.com/photo-1688732324812-9c67f0a35b4b?w=400', 'Home Decor', 'https://www.aliexpress.com', 72, 'Rising', true, NOW() - INTERVAL '48 days'),
('Ceramic Butter Dish with Lid', 'Covered ceramic butter dish for counter-safe soft butter — a niche but reliably evergreen kitchen-decor crossover SKU with strong repeat-purchase potential as a gift-set add-on.', 'https://images.unsplash.com/photo-1591632288574-a387f820a1ca?w=400', 'Home Decor', 'https://www.aliexpress.com', 70, 'Rising', true, NOW() - INTERVAL '59 days'),
('Woven Wall Basket Decor Set', 'Set of three graduated woven baskets arranged as wall art — a proven "gallery wall alternative" with strong boho and farmhouse appeal and cheap flat-pack shipping.', 'https://images.unsplash.com/photo-1578678809626-a3741782f0b8?w=400', 'Home Decor', 'https://www.aliexpress.com', 78, 'Trending', true, NOW() - INTERVAL '20 days'),

-- Kitchen Gadgets (15)
('Electric Herb Scissors Stripper', 'Multi-blade electric herb scissors that mince fresh herbs in seconds — a genuine time-saver with strong "kitchen hack" short-form video appeal among home cooks and meal-preppers.', 'https://images.unsplash.com/photo-1691391611977-198acc8d43b2?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 76, 'Rising', true, NOW() - INTERVAL '11 days'),
('Electric Spice Grinder', 'One-touch electric spice grinder for fresh peppercorns, herbs, and salt — a reliable evergreen SKU for the home-cooking audience with strong "fresh vs. store-bought" ad angle.', 'https://images.unsplash.com/photo-1765120828124-f3217ba51a09?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 74, 'Rising', true, NOW() - INTERVAL '41 days'),
('Leak-Proof Silicone Sandwich Bags Set', 'Reusable silicone sandwich and snack bags that replace single-use plastic — strong eco-angle messaging paired with real cost savings, a proven combination for conversion.', 'https://images.unsplash.com/photo-1606859191214-25806e8e2423?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 85, 'Trending', true, NOW() - INTERVAL '5 days'),
('Adjustable Rolling Pin with Measuring Rings', 'Rolling pin with removable measuring rings for consistent dough thickness — a genuinely useful baking-precision tool with strong appeal to the home-baking content niche.', 'https://images.unsplash.com/photo-1608874755008-2d27ecc04870?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 71, 'Rising', true, NOW() - INTERVAL '55 days'),
('Belgian Waffle Iron Maker', 'Compact Belgian waffle maker with a deep-pocket nonstick plate — a strong "weekend breakfast" ad angle with broad, non-niche appeal and satisfying demo footage.', 'https://images.unsplash.com/photo-1761385465043-b3f4cb0976bb?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 82, 'Trending', true, NOW() - INTERVAL '8 days'),
('Garlic Press Mincer Tool', 'Self-cleaning garlic press that mince without peeling first — a small, cheap-to-ship, genuinely useful kitchen staple with consistent year-round demand.', 'https://images.unsplash.com/photo-1639119677984-b6c9ed1b0ca8?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 73, 'Rising', true, NOW() - INTERVAL '33 days'),
('Silicone Baking Mat Set', 'Reusable non-stick silicone baking mats that replace parchment paper — an eco-angle staple with strong repeat interest from the home-baking and meal-prep audience.', 'https://images.unsplash.com/photo-1729308233730-8233e01007e0?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 77, 'Rising', true, NOW() - INTERVAL '27 days'),
('Air Fryer Silicone Liners Set', 'Reusable silicone air fryer liners that eliminate scrubbing and disposable parchment — riding the still-surging air fryer accessory wave with genuine daily-use utility.', 'https://images.unsplash.com/photo-1774074645537-f72f70d40d12?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 91, 'Hot', true, NOW() - INTERVAL '1 days'),
('Electric Milk Frother Wand', 'Handheld electric milk frother that makes café-style foam in seconds — a strong "coffee at home" ad angle riding the sustained home-barista trend with broad appeal.', 'https://images.unsplash.com/photo-1611832567923-99dba19bd155?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 84, 'Trending', true, NOW() - INTERVAL '13 days'),
('Stackable Fridge Organizer Bins', 'Clear stackable fridge bins that turn a chaotic fridge into a satisfying "organize with me" reveal — one of the most reliably viral kitchen-organization categories right now.', 'https://images.unsplash.com/photo-1611871962470-f86cba5c7e8e?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 88, 'Hot', true, NOW() - INTERVAL '3 days'),
('Meat Shredder Claws Set', 'Sturdy meat-shredding claws for pulled pork and chicken — a specific, high-intent purchase from the home-BBQ and meal-prep audience with satisfying demo footage.', 'https://images.unsplash.com/photo-1445979323117-80453f573b71?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 79, 'Trending', true, NOW() - INTERVAL '19 days'),
('Instant Pot Egg Bite Mold', 'Silicone egg bite mold sized for pressure cookers — rides the sustained high-protein breakfast meal-prep trend with a clear, repeatable weekly-use case.', 'https://images.unsplash.com/photo-1767425315674-26de4751638f?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 75, 'Rising', true, NOW() - INTERVAL '44 days'),
('Citrus Juicer Hand Press', 'Cast manual citrus press for fresh lemon and lime juice — a compact, cheap-to-ship staple with consistent demand from the home-cocktail and healthy-eating audiences.', 'https://images.unsplash.com/photo-1750675632479-ec901f3d4a5f?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 78, 'Trending', true, NOW() - INTERVAL '25 days'),
('Bread Proofing Basket Set', 'Rattan banneton proofing baskets for home sourdough bakers — rides the still-strong home-baking trend with a passionate, repeat-purchasing niche audience.', 'https://images.unsplash.com/photo-1609889132680-4e2ea2befbef?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 72, 'Rising', true, NOW() - INTERVAL '50 days'),
('Magnetic Measuring Spoons Set', 'Nesting magnetic measuring spoons that snap together for compact storage — a small quality-of-life upgrade with strong "kitchen hack" short-form appeal.', 'https://images.unsplash.com/photo-1781082591998-1f6f2bda66e2?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 80, 'Trending', true, NOW() - INTERVAL '16 days'),

-- Pet Supplies (12)
('Automatic Ball Launcher for Dogs', 'Motorized ball launcher that plays fetch hands-free — a premium SKU tapping into the "working pet owner" audience with strong perceived value and satisfying demo footage.', 'https://images.unsplash.com/photo-1612502169027-5a379283f9c0?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 90, 'Hot', true, NOW() - INTERVAL '2 days'),
('Pet Hair Removal Roller Brush', 'Self-cleaning pet hair roller for furniture and car seats — a genuinely useful, high-frequency-use tool with strong "before and after" ad-angle potential.', 'https://images.unsplash.com/photo-1528846104175-4fd300ee59da?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 76, 'Rising', true, NOW() - INTERVAL '37 days'),
('Bolster Memory Foam Dog Bed', 'Raised-edge memory foam dog bed aimed at senior and large-breed dogs — a higher-AOV SKU with a genuine health angle that resonates strongly with devoted pet owners.', 'https://images.unsplash.com/photo-1598397678815-c5dc869035b8?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 83, 'Trending', true, NOW() - INTERVAL '10 days'),
('Cat Scratching Cardboard Lounge', 'Curved cardboard scratching lounge that doubles as a bed — a proven cat-content category with strong repeat-purchase economics as replacement pads wear out.', 'https://images.unsplash.com/photo-1636543459630-8975a3548121?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 79, 'Trending', true, NOW() - INTERVAL '22 days'),
('Dog Puzzle Feeder Toy', 'Slow-release puzzle feeder that slows down fast eaters while providing mental stimulation — a vet-recommended upgrade with a clear, specific pain-point angle.', 'https://images.unsplash.com/photo-1627323721367-94128c3fa0f7?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 81, 'Trending', true, NOW() - INTERVAL '15 days'),
('Pet Car Seat Belt Leash', 'Adjustable seatbelt-clip leash that keeps dogs safely restrained on car rides — a genuine safety angle that resonates strongly with the road-tripping pet-owner audience.', 'https://images.unsplash.com/photo-1708062270853-ee7c66b69f07?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 74, 'Rising', true, NOW() - INTERVAL '43 days'),
('Collapsible Travel Pet Bowl', 'Silicone collapsible bowl that folds flat for travel and hiking — a compact, cheap-to-ship SKU with strong appeal to the outdoor-adventure pet-owner niche.', 'https://images.unsplash.com/photo-1679224106783-c21b1841412a?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 77, 'Rising', true, NOW() - INTERVAL '29 days'),
('Cat Litter Mat Trapper', 'Honeycomb-textured litter trapping mat that catches stray litter before it spreads — a genuinely useful daily-use product with a specific, high-intent pain-point angle.', 'https://images.unsplash.com/photo-1625241589108-d4ceb8dbcc4d?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 78, 'Trending', true, NOW() - INTERVAL '24 days'),
('Dog Anxiety Calming Bed', 'Donut-shaped calming bed with raised rim that mimics being held — a strong emotional ad angle backed by genuine anxious-pet demand, with broad appeal across breeds.', 'https://images.unsplash.com/photo-1646195164326-124b72fb9d34?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 86, 'Trending', true, NOW() - INTERVAL '7 days'),
('Pet Hair Dryer Grooming Blower', 'Low-noise pet dryer designed to keep anxious dogs calm during at-home grooming — a premium SKU with a clear "save money on the groomer" angle.', 'https://images.unsplash.com/photo-1625321171045-1fea4ac688e9?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 75, 'Rising', true, NOW() - INTERVAL '39 days'),
('Interactive Laser Cat Toy', 'Automatic laser toy with randomized movement patterns that keeps cats entertained solo — a strong "working from home guilt" ad angle with satisfying demo footage.', 'https://images.unsplash.com/photo-1636543459788-98fc50866d60?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 82, 'Trending', true, NOW() - INTERVAL '18 days'),
('Dog Muzzle Adjustable Mesh', 'Breathable adjustable mesh muzzle for vet visits and grooming — a practical safety accessory with steady, non-seasonal demand across nervous and reactive dogs.', 'https://images.unsplash.com/photo-1580129518863-f00fcf1d6e68?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 71, 'Rising', true, NOW() - INTERVAL '53 days'),

-- Beauty & Skincare (12)
('LED Face Mask Light Therapy', 'Multi-wavelength LED face mask targeting acne, fine lines, and skin tone — one of the most consistently viral at-home skincare-device categories with strong before/after content potential.', 'https://images.unsplash.com/photo-1559818447-969ea3aa2fbd?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 92, 'Hot', true, NOW() - INTERVAL '1 days'),
('Dermaplaning Facial Tool Set', 'At-home dermaplaning tool for peach fuzz and gentle exfoliation — a strong ingredient-story and technique-driven ad angle with high repeat-purchase potential on replacement blades.', 'https://images.unsplash.com/photo-1573248301651-7656b7aa4dfe?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 80, 'Trending', true, NOW() - INTERVAL '12 days'),
('Jade Roller and Gua Sha Combo Kit', 'Matching jade roller and gua sha stone set for at-home facial massage — a proven "morning routine" staple with consistent demand and strong self-care content appeal.', 'https://images.unsplash.com/photo-1643379855889-850035817d24?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 84, 'Trending', true, NOW() - INTERVAL '9 days'),
('Facial Steamer Nano Ionic', 'Nano-ionic facial steamer that opens pores before a skincare routine — a premium at-home spa-day SKU with strong before/after and self-care content potential.', 'https://images.unsplash.com/photo-1602516793068-35b73edf3368?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 87, 'Trending', true, NOW() - INTERVAL '4 days'),
('Silicone Makeup Brush Cleaner Mat', 'Textured silicone mat that scrubs makeup brushes clean in seconds — a genuinely useful, cheap-to-ship accessory with strong "clean girl" content appeal.', 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 73, 'Rising', true, NOW() - INTERVAL '46 days'),
('Hair Scalp Massager Shampoo Brush', 'Silicone scalp massager brush that turns shower time into a self-care moment — a low-cost, high-margin SKU with strong "shower routine" short-form video appeal.', 'https://images.unsplash.com/photo-1595475884562-073c30d45670?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 85, 'Trending', true, NOW() - INTERVAL '6 days'),
('Retinol Night Cream Jar', 'Nightly retinol cream targeting fine lines and texture — an evergreen skincare staple with strong repeat-purchase economics once a customer builds it into their routine.', 'https://images.unsplash.com/photo-1638609927040-8a7e97cd9d6a?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 76, 'Rising', true, NOW() - INTERVAL '35 days'),
('Facial Ice Globes Cooling Tool', 'Cooling glass globes for depuffing and lymphatic massage — a low-cost, high-margin "morning routine" staple with a satisfying, visually distinct demo.', 'https://images.unsplash.com/photo-1564512480295-86e479d9b87c?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 79, 'Trending', true, NOW() - INTERVAL '21 days'),
('Electric Callus Remover Foot File', 'Rechargeable electric foot file that removes hard skin in seconds — a strong "at-home pedicure" ad angle with genuine before/after content potential.', 'https://images.unsplash.com/photo-1664643411326-6c589531be3c?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 74, 'Rising', true, NOW() - INTERVAL '49 days'),
('Under Eye Collagen Patches Set', 'Hydrogel under-eye patches for puffiness and dark circles — a proven, highly shareable "quick fix" beauty category with strong impulse-buy pricing and repeat-purchase potential.', 'https://images.unsplash.com/photo-1773754723152-0a31954e3036?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 88, 'Hot', true, NOW() - INTERVAL '3 days'),
('Rose Quartz Gua Sha Set', 'Genuine rose quartz gua sha tool for facial sculpting and lymphatic drainage — rides the sustained crystal-skincare trend with strong self-care and gifting appeal.', 'https://images.unsplash.com/photo-1665378764540-8aca31360df9?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 81, 'Trending', true, NOW() - INTERVAL '15 days'),
('Makeup Organizer Rotating Tower', '360-degree rotating makeup organizer that fits a full collection on one countertop — a strong "vanity glow-up" ad angle with broad appeal across the beauty-enthusiast audience.', 'https://images.unsplash.com/photo-1766242281507-dca096a98464?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 72, 'Rising', true, NOW() - INTERVAL '51 days'),

-- Fitness (10)
('Adjustable Ab Wheel with Knee Pad', 'Core-training ab wheel bundled with a knee pad for comfort — a staple in home-gym starter kits with extremely low cost of goods and strong margin.', 'https://images.unsplash.com/photo-1600026453346-a44501602a02?w=400', 'Fitness', 'https://www.aliexpress.com', 78, 'Trending', true, NOW() - INTERVAL '26 days'),
('Gymnastic Rings Set with Straps', 'Adjustable-strap gymnastic rings for calisthenics and bodyweight training — rides the sustained home-gym and functional-fitness trend with strong appeal to intermediate lifters.', 'https://images.unsplash.com/photo-1687349815539-047059cdc478?w=400', 'Fitness', 'https://www.aliexpress.com', 82, 'Trending', true, NOW() - INTERVAL '14 days'),
('Weighted Hula Hoop for Exercise', 'Segmented weighted hula hoop marketed as a low-impact core workout — a proven viral fitness category with strong before/after and "10 minutes a day" content potential.', 'https://images.unsplash.com/photo-1605021272777-72805ea0c9c8?w=400', 'Fitness', 'https://www.aliexpress.com', 86, 'Trending', true, NOW() - INTERVAL '8 days'),
('Balance Pad Stability Trainer', 'High-density foam balance pad for stability and rehab training — a reliable evergreen SKU with appeal across athletes, physical therapy patients, and casual gym-goers.', 'https://images.unsplash.com/photo-1550345332-d73a0111ad25?w=400', 'Fitness', 'https://www.aliexpress.com', 73, 'Rising', true, NOW() - INTERVAL '47 days'),
('Door Anchor Resistance Band Kit', 'Full resistance band set with a door anchor for cable-style home workouts — a top-performing home-fitness category with strong repeat interest and broad exercise variety.', 'https://images.unsplash.com/photo-1584827386916-b5351d3ba34b?w=400', 'Fitness', 'https://www.aliexpress.com', 80, 'Trending', true, NOW() - INTERVAL '19 days'),
('Compression Leg Sleeves Pair', 'Graduated compression leg sleeves for recovery and circulation during workouts or long flights — a specific, high-intent purchase with strong appeal to runners and travelers alike.', 'https://images.unsplash.com/photo-1783632895890-a3b05fae1754?w=400', 'Fitness', 'https://www.aliexpress.com', 75, 'Rising', true, NOW() - INTERVAL '42 days'),
('Cooling Towel for Workout', 'Instant-cooling microfiber towel that stays cold with a simple snap and wring — a low-cost, high-margin accessory with strong seasonal demand every spring and summer.', 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400', 'Fitness', 'https://www.aliexpress.com', 71, 'Rising', true, NOW() - INTERVAL '57 days'),
('Adjustable Kettlebell Set', 'Space-saving adjustable kettlebell that replaces a full rack — a higher-AOV home-gym SKU riding the sustained at-home fitness trend with strong upsell potential.', 'https://images.unsplash.com/photo-1562771241-2e852edfce63?w=400', 'Fitness', 'https://www.aliexpress.com', 83, 'Trending', true, NOW() - INTERVAL '11 days'),
('Sliding Core Disc Exercise Gliders', 'Dual-sided gliding discs for low-impact core and full-body sliding exercises — a cheap-to-ship, high-margin accessory popular in the home-Pilates content niche.', 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=400', 'Fitness', 'https://www.aliexpress.com', 77, 'Rising', true, NOW() - INTERVAL '32 days'),
('Push Up Board System', 'Color-coded push-up board with rotating handles targeting different muscle groups — a strong "one tool, full workout" ad angle with broad appeal to home-gym beginners.', 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=400', 'Fitness', 'https://www.aliexpress.com', 79, 'Trending', true, NOW() - INTERVAL '23 days'),

-- Tech Accessories (10)
('MagSafe Compatible Wallet Card Holder', 'Magnetic card wallet that snaps directly onto MagSafe-compatible phones — a strong "one less thing to carry" ad angle with broad, non-niche appeal and excellent shipping economics.', 'https://images.unsplash.com/photo-1624538000860-24716b9050f2?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 85, 'Trending', true, NOW() - INTERVAL '6 days'),
('Adjustable Laptop Webcam Light', 'Clip-on ring light designed specifically for laptop webcams — rides the sustained remote-work and video-call content trend with a clear, specific pain-point angle.', 'https://images.unsplash.com/photo-1726127461372-547b9ffa4236?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 74, 'Rising', true, NOW() - INTERVAL '40 days'),
('Laptop Cooling Pad with Fans', 'Multi-fan laptop cooling pad that keeps devices running quiet under heavy load — a genuinely useful accessory for the gaming and remote-work audience with steady year-round demand.', 'https://images.unsplash.com/photo-1629317480826-910f729d1709?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 81, 'Trending', true, NOW() - INTERVAL '17 days'),
('Microfiber Screen Cleaning Spray Kit', 'Anti-static screen cleaning spray with a microfiber cloth — a low-cost, high-margin accessory with broad appeal and easy bundling with any electronics purchase.', 'https://images.unsplash.com/photo-1616440347437-b1c73416efc2?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 70, 'Rising', true, NOW() - INTERVAL '58 days'),
('Under Desk Cable Management Tray', 'Adhesive-mount cable tray that hides power strips and cords under a desk — rides the sustained "desk setup" content trend with a strong satisfying before/after angle.', 'https://images.unsplash.com/photo-1614624532983-4ce03382d63d?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 76, 'Rising', true, NOW() - INTERVAL '36 days'),
('Wireless Charging Stand 3-in-1', '3-in-1 charging stand for phone, watch, and earbuds in one dock — a premium desk-setup SKU with strong perceived value and broad appeal across Apple and Android users.', 'https://images.unsplash.com/photo-1591290619618-904f6dd935e3?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 89, 'Hot', true, NOW() - INTERVAL '2 days'),
('Foldable Bluetooth Keyboard', 'Pocket-sized foldable Bluetooth keyboard for tablets and phones on the go — a strong "digital nomad" ad angle with genuine daily-use utility for remote workers and students.', 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 78, 'Trending', true, NOW() - INTERVAL '24 days'),
('Portable Monitor for Laptop', 'Slim USB-C portable second monitor that turns any laptop into a dual-screen setup — a higher-AOV productivity SKU with strong appeal to the remote-work and content-creator audience.', 'https://images.unsplash.com/photo-1510519138101-570d1dca3d66?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 82, 'Trending', true, NOW() - INTERVAL '13 days'),
('USB Desktop Microphone', 'Plug-and-play USB condenser microphone for podcasting and streaming — rides the sustained content-creator boom with a clear, specific audience and strong upsell potential to a boom-arm mount.', 'https://images.unsplash.com/photo-1614588876378-b2ffa4520c22?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 84, 'Trending', true, NOW() - INTERVAL '9 days'),
('Ergonomic Vertical Mouse', 'Vertical ergonomic mouse targeting the "wrist pain from WFH" audience — a specific, high-intent pain-point angle that converts well on informational ad creative.', 'https://images.unsplash.com/photo-1596495717655-5a38ee8ad7b2?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 75, 'Rising', true, NOW() - INTERVAL '34 days'),

-- Baby & Kids (8)
('Portable Baby Sound Soother', 'Compact travel sound soother with white noise and lullabies for naps on the go — a strong "sleep-training win" ad angle that resonates deeply with sleep-deprived parents.', 'https://images.unsplash.com/photo-1626856295349-6f21d6e6cfef?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 83, 'Trending', true, NOW() - INTERVAL '10 days'),
('Baby Food Maker Steamer Blender', 'All-in-one steamer and blender that makes fresh baby food in one appliance — a strong "healthier than store-bought" ad angle with genuine cost-saving appeal for new parents.', 'https://images.unsplash.com/photo-1652480275137-9de7ef17a0a3?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 87, 'Trending', true, NOW() - INTERVAL '4 days'),
('Foldable Bath Kneeler Pad', 'Cushioned kneeling and elbow-rest pad that makes bath time easier on parents'' knees and back — a genuine comfort angle with broad appeal across the new-parent audience.', 'https://images.unsplash.com/photo-1609220361664-a5cd02bc7345?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 76, 'Rising', true, NOW() - INTERVAL '30 days'),
('Baby Star Ceiling Projector', 'Star and nebula ceiling projector with soothing sounds for the nursery — one of the most consistently viral baby-registry categories with strong gifting and "nursery tour" content appeal.', 'https://images.unsplash.com/photo-1587023705100-8094f8d47e86?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 90, 'Hot', true, NOW() - INTERVAL '1 days'),
('Silicone Suction Baby Plate Set', 'Suction-base silicone plate and bowl set that stays put through toddler meals — a genuinely useful mess-reduction product with strong "mom hack" short-form video appeal.', 'https://images.unsplash.com/photo-1646314951096-ed41d80638b6?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 79, 'Trending', true, NOW() - INTERVAL '20 days'),
('Baby Sleep Swaddle Wrap', 'Adjustable swaddle wrap designed to ease the startle reflex for better newborn sleep — a strong "finally, sleep" ad angle that speaks directly to exhausted new parents.', 'https://images.unsplash.com/photo-1773243086631-962baefccd8a?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 81, 'Trending', true, NOW() - INTERVAL '16 days'),
('Kids Learning Tower Stool', 'Adjustable-height learning tower that safely lets toddlers help at the counter — a premium Montessori-aligned SKU with strong appeal to the intentional-parenting audience.', 'https://images.unsplash.com/photo-1612200057237-59ff4c861453?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 74, 'Rising', true, NOW() - INTERVAL '44 days'),
('Baby Proofing Cabinet Locks Set', 'No-drill adhesive cabinet and drawer locks for childproofing — a practical safety SKU with steady, non-seasonal demand from every new-crawler household.', 'https://images.unsplash.com/photo-1775346395915-de166255b53c?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 72, 'Rising', true, NOW() - INTERVAL '54 days'),

-- Car Accessories (8)
('Car Diffuser Essential Oil Vent Clip', 'Vent-clip essential oil diffuser that freshens a car without sprays or plug-ins — a low-cost, high-margin accessory with strong repeat-purchase potential on refill oils.', 'https://images.unsplash.com/photo-1636763086471-9f29bc34ab9e?w=400', 'Car Accessories', 'https://www.aliexpress.com', 77, 'Rising', true, NOW() - INTERVAL '28 days'),
('Backseat Tablet Holder Mount', 'Adjustable headrest mount that holds a tablet for backseat entertainment — a strong "road trip saver" ad angle that speaks directly to parents of young kids.', 'https://images.unsplash.com/photo-1547731269-e4073e054f12?w=400', 'Car Accessories', 'https://www.aliexpress.com', 80, 'Trending', true, NOW() - INTERVAL '18 days'),
('Car Trunk Cargo Net Organizer', 'Elastic cargo net that keeps groceries and gear from sliding around the trunk — a genuinely useful, cheap-to-ship accessory with broad appeal across every driver.', 'https://images.unsplash.com/photo-1631844321841-f6e67698158f?w=400', 'Car Accessories', 'https://www.aliexpress.com', 73, 'Rising', true, NOW() - INTERVAL '46 days'),
('Leather Car Seat Cushion Set', 'Ergonomic memory foam seat cushion with a leather finish for long commutes — a strong comfort angle with genuine appeal to rideshare drivers and long-distance commuters.', 'https://images.unsplash.com/photo-1616196334411-1d8d09708ca6?w=400', 'Car Accessories', 'https://www.aliexpress.com', 78, 'Trending', true, NOW() - INTERVAL '25 days'),
('Car Phone Wireless Charger Mount', 'Auto-clamping wireless charging mount that grips a phone and charges it hands-free — a strong daily-use safety angle with broad, non-niche appeal.', 'https://images.unsplash.com/photo-1610647752706-3bb12232b3ab?w=400', 'Car Accessories', 'https://www.aliexpress.com', 84, 'Trending', true, NOW() - INTERVAL '7 days'),
('Tire Pressure Gauge Digital', 'Digital tire pressure gauge with an easy-read backlit display — a practical, evergreen car-maintenance SKU with steady demand across every vehicle owner.', 'https://images.unsplash.com/photo-1444947295498-07f60c19a4ff?w=400', 'Car Accessories', 'https://www.aliexpress.com', 71, 'Rising', true, NOW() - INTERVAL '52 days'),
('Car Sunshade for Side Windows Set', 'Static-cling side window sunshades that block glare and UV for backseat passengers — a strong seasonal SKU every spring and summer with a clear parent-focused angle.', 'https://images.unsplash.com/photo-1549064233-945d7063292f?w=400', 'Car Accessories', 'https://www.aliexpress.com', 75, 'Rising', true, NOW() - INTERVAL '38 days'),
('Portable Car Jump Starter', 'Compact lithium jump starter that fits in a glovebox — a premium, genuinely useful safety SKU with strong "never get stranded again" ad-angle potential.', 'https://images.unsplash.com/photo-1602161755661-3781cddac355?w=400', 'Car Accessories', 'https://www.aliexpress.com', 86, 'Trending', true, NOW() - INTERVAL '5 days'),

-- Outdoor & Garden (10)
('Solar Powered Motion Sensor Lights', 'Wireless solar lights that trigger on motion for driveways and pathways — a strong "no wiring needed" ad angle with genuine security appeal and consistent demand.', 'https://images.unsplash.com/photo-1612670924115-ee24dd0c0d91?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 88, 'Hot', true, NOW() - INTERVAL '3 days'),
('Ceramic Bird Bath Bowl', 'Weather-resistant ceramic bird bath bowl that mounts on any garden stand or pedestal — a proven backyard-birding category with steady, passionate repeat-purchase demand.', 'https://images.unsplash.com/photo-1649256282262-b0cbd6e420c6?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 74, 'Rising', true, NOW() - INTERVAL '41 days'),
('Digital Outdoor Thermometer Hygrometer', 'Wireless outdoor thermometer and humidity gauge with an indoor display — a practical, evergreen SKU with steady demand from gardeners and greenhouse hobbyists.', 'https://images.unsplash.com/photo-1609725236589-d987ffc8133a?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 72, 'Rising', true, NOW() - INTERVAL '49 days'),
('Foldable Garden Kneeling Stool with Tools', 'Padded kneeling stool that folds into a tool seat, with a built-in pouch for hand tools — a genuine comfort angle with strong appeal to the home-gardening audience.', 'https://images.unsplash.com/photo-1523301551780-cd17359a95d0?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 77, 'Rising', true, NOW() - INTERVAL '31 days'),
('Vertical Garden Planter Tower', 'Stackable vertical planter tower that grows a full herb or strawberry garden in a small footprint — a strong "small space gardening" ad angle with broad urban-dweller appeal.', 'https://images.unsplash.com/photo-1682629088818-1ec55d0cf45b?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 82, 'Trending', true, NOW() - INTERVAL '12 days'),
('Solar Garden Lantern Stakes', 'Set of solar-powered lantern stakes that line a garden path with warm ambient light — a strong "outdoor glow-up" ad angle riding the backyard-entertaining trend.', 'https://images.unsplash.com/photo-1774268502832-e6de1c03c01e?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 79, 'Trending', true, NOW() - INTERVAL '22 days'),
('Garden Tool Storage Rack', 'Wall-mounted rack that organizes shovels, rakes, and hand tools in a garage or shed — a satisfying "organize with me" SKU with genuine daily-use utility.', 'https://images.unsplash.com/photo-1526381805515-3fec2d69e7cc?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 73, 'Rising', true, NOW() - INTERVAL '47 days'),
('Wall-Mounted Garden Hose Reel', 'Retractable wall-mounted reel that keeps a garden hose neatly wound and off the ground — a practical upgrade with strong appeal to the home-improvement and lawn-care audience.', 'https://images.unsplash.com/photo-1688993399248-84c227bc7020?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 76, 'Rising', true, NOW() - INTERVAL '35 days'),
('Outdoor Weatherproof Cushion Covers', 'Water-resistant replacement cushion covers that refresh patio furniture without buying new pieces — a strong "patio glow-up" ad angle with a clear cost-saving pitch.', 'https://images.unsplash.com/photo-1760533535801-20dc5fca0fb0?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 80, 'Trending', true, NOW() - INTERVAL '19 days'),
('Mosquito Repellent Solar Lantern', 'Solar-powered lantern with a built-in mosquito-repelling function for patios and campsites — a strong seasonal SKU every spring and summer with a clear, specific pain-point angle.', 'https://images.unsplash.com/photo-1577302463975-bf68e799e79d?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 85, 'Trending', true, NOW() - INTERVAL '6 days');
