-- Batch 2: 50 additional winning dropshipping products across 9 niches.
-- Every image_url was chosen from a live Unsplash search for that specific
-- product and verified to return HTTP 200 / image/jpeg before being added
-- here (same process used for the batch-1 image relevance fix).

INSERT INTO products (title, description, image_url, niche, supplier_url, demand_score, trend_label, is_featured) VALUES

-- Home Decor (8)
('LED Neon Sign Custom Wall Art', 'Customizable LED neon-effect wall sign that''s become a staple in "room makeover" TikToks and Instagram Reels. High perceived value, low shipping weight, and a huge upsell opportunity via custom text/color options.', 'https://images.unsplash.com/photo-1631058269796-6ea2654cc78b?w=400', 'Home Decor', 'https://www.aliexpress.com', 89, 'Hot', true),
('Boho Round Wall Mirror', 'Rattan-framed round mirror that anchors the "boho apartment" aesthetic dominating home decor content right now. Lightweight for shipping despite its large visual footprint, with strong repeat interest across multiple room styles.', 'https://images.unsplash.com/photo-1618220252344-8ec99ec624b1?w=400', 'Home Decor', 'https://www.aliexpress.com', 81, 'Trending', true),
('Woven Storage Basket Set', 'Stackable woven baskets that solve real clutter problems while looking intentional on a shelf. Nests for cheap shipping, sells well as a 3-pack bundle, and pairs naturally with the minimalist-organization niche.', 'https://images.unsplash.com/photo-1645542554266-b275c100103c?w=400', 'Home Decor', 'https://www.aliexpress.com', 76, 'Rising', true),
('Cloud Shaped Throw Pillow', 'Oversized cloud-shaped accent pillow that consistently pops up in "cozy room" Pinterest boards. Novelty shape drives impulse buys, and it ships flat/compressed for a great margin.', 'https://images.unsplash.com/photo-1573846593549-95ca60ebb7ad?w=400', 'Home Decor', 'https://www.aliexpress.com', 74, 'Rising', true),
('Abstract Line Art Canvas Print Set', 'Minimalist line-art canvas prints sold as a matching 3-piece set — one of the highest-converting "wall art bundle" categories on Meta ads right now. No assembly, ships flat, broad appeal across styles.', 'https://images.unsplash.com/photo-1765498173413-b428f5d0a17e?w=400', 'Home Decor', 'https://www.aliexpress.com', 83, 'Trending', true),
('Wall-Mounted Plant Shelf Set', 'Floating shelf set designed specifically for displaying small potted plants, tapping into both the plant-parent and home-organization audiences at once. Easy install angle makes for strong short-form demo content.', 'https://images.unsplash.com/photo-1677537164970-b5a3345b59f6?w=400', 'Home Decor', 'https://www.aliexpress.com', 79, 'Trending', true),
('Aromatherapy Diffuser Humidifier Lamp', 'Combo essential-oil diffuser, humidifier, and mood lamp — a three-in-one value prop that consistently outsells single-function diffusers. Strong "self-care setup" UGC potential.', 'https://images.unsplash.com/photo-1768471569643-717e823b5f9a?w=400', 'Home Decor', 'https://www.aliexpress.com', 85, 'Trending', true),
('Velvet Storage Ottoman Bench', 'Upholstered storage ottoman that doubles as seating and hidden storage — a favorite in small-apartment and bedroom-makeover content. Higher AOV than most decor SKUs with solid margin room.', 'https://images.unsplash.com/photo-1782875574733-501ccdb0add3?w=400', 'Home Decor', 'https://www.aliexpress.com', 77, 'Rising', true),

-- Kitchen Gadgets (7)
('Handheld Electric Spin Scrubber', 'Cordless power scrubber that went viral for cutting bathroom and kitchen cleaning time in half — a top "oddly satisfying" product category on TikTok Shop. Comes with swappable brush heads for cross-sell.', 'https://images.unsplash.com/photo-1772911141529-f24dae5926c1?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 88, 'Hot', true),
('Rechargeable Cordless Electric Whisk', 'USB-rechargeable mini whisk for eggs, batter, and frothing — small, cheap to ship, and a frequent "kitchen hack" video subject. Strong impulse-buy price point.', 'https://images.unsplash.com/photo-1638792958866-9b3f787ec709?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 75, 'Rising', true),
('Magnetic Wall-Mount Knife Strip', 'Space-saving magnetic knife strip that''s a recurring feature in small-kitchen organization content. Simple, durable, and pairs well as an add-on to a knife-set offer.', 'https://images.unsplash.com/photo-1710947950298-680192e57f5a?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 73, 'Rising', true),
('Collapsible Silicone Colander Set', 'Space-saving silicone colanders that collapse flat for storage — a strong "small kitchen hacks" ad angle with genuinely useful everyday function. Nesting design keeps shipping costs low.', 'https://images.unsplash.com/photo-1767327811909-05198eddd64f?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 78, 'Trending', true),
('Stainless Steel Avocado Slicer Tool', '3-in-1 avocado tool (splits, pits, and slices) riding the sustained avocado-toast trend. Extremely low cost of goods with strong markup potential and easy short-form demo appeal.', 'https://images.unsplash.com/photo-1605522599721-c18480409d58?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 72, 'Rising', true),
('Reusable Silicone Stretch Lids Set', 'Stretchable silicone lids that replace plastic wrap — strong eco-angle messaging that resonates with sustainability-minded buyers. Sold as a multi-size set for higher AOV.', 'https://images.unsplash.com/photo-1585166443364-7304b3a9b725?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 80, 'Trending', true),
('Mini Electric Waffle Maker', 'Compact single-serve waffle maker sized for dorms and small kitchens, a recurring "cute kitchen appliance" viral category. Gift-friendly packaging drives conversion during Q4.', 'https://images.unsplash.com/photo-1485629066172-81a49ed3aa29?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 82, 'Trending', true),

-- Pet Supplies (6)
('Multi-Level Cat Scratching Post Tower', 'Tall multi-platform cat tree that satisfies scratching, climbing, and lounging in one purchase — consistently one of the highest-AOV pet SKUs. Strong repeat interest from multi-cat households.', 'https://images.unsplash.com/photo-1636543459633-53c7216fee3c?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 84, 'Trending', true),
('Dog Training Clicker Set', 'Simple clicker + treat pouch combo aimed at the huge "new puppy owner" audience segment. Low cost of goods, evergreen demand tied to pet adoption cycles.', 'https://images.unsplash.com/photo-1640652663796-764e4eb5bc59?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 73, 'Rising', true),
('Silicone Pet Grooming Glove', 'Deshedding glove that turns petting into grooming — a strong "before/after fur pile" video hook. Fits both cats and dogs, widening the target audience.', 'https://images.unsplash.com/photo-1681305761221-1d0baf420eb0?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 79, 'Trending', true),
('Elevated Pet Feeding Station', 'Raised feeding stand that improves posture for larger dogs and reduces mess — a common vet-recommended upgrade that converts well on informational ad angles. Higher AOV than flat bowls.', 'https://images.unsplash.com/photo-1677973591478-41b5b97d7738?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 76, 'Rising', true),
('Interactive Motion Cat Toy Ball', 'Self-rolling, motion-activated toy ball that keeps cats engaged solo — a strong "home alone pet" pain-point angle for working owners. Highly shareable in cat-reaction content.', 'https://images.unsplash.com/photo-1652757557322-c03b84925cd6?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 87, 'Trending', true),
('Waterproof Pet Car Seat Cover', 'Full-bench waterproof cover that protects car seats from fur, mud, and scratches — a practical, high-intent purchase for dog owners who travel often. Strong seasonal spike around road-trip season.', 'https://images.unsplash.com/photo-1559092209-3fef6ee67887?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 74, 'Rising', true),

-- Beauty & Skincare (6)
('Gua Sha Facial Tool Set', 'Rose quartz gua sha set riding the sustained "facial sculpting" wave across TikTok and Instagram skincare content. Extremely low cost of goods with strong tutorial-driven organic reach potential.', 'https://images.unsplash.com/photo-1643379855122-3d3162b56a99?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 86, 'Trending', true),
('Vitamin C Brightening Serum', 'Best-selling active-ingredient serum category with consistent search volume and strong repeat-purchase economics once a customer converts. Works well bundled with other skincare SKUs.', 'https://images.unsplash.com/photo-1745159338135-39f6b462b382?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 90, 'Hot', true),
('LED Teeth Whitening Kit', 'At-home LED whitening kit with strong before/after UGC potential — one of the most consistently profitable beauty categories for creator-led ad campaigns. High perceived value at a low unit cost.', 'https://images.unsplash.com/photo-1677026010083-78ec7f1b84ed?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 85, 'Trending', true),
('Silicone Facial Cleansing Brush', 'Vibrating silicone cleansing brush that pairs naturally with any skincare routine offer. Easy to demo in a 15-second video, driving strong organic and paid conversion alike.', 'https://images.unsplash.com/photo-1761718209835-c8586b7dcac0?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 78, 'Trending', true),
('Rose Quartz Facial Roller Set', 'Crystal facial roller paired with a gua sha tool — a classic "self-care gift set" bundle that performs especially well in Q4. Low weight keeps shipping costs minimal.', 'https://images.unsplash.com/photo-1593259213062-57b0ce5906cf?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 75, 'Rising', true),
('Collagen Overnight Sleep Mask', 'Leave-on overnight mask targeting the "wake up glowing" content trend, with strong ingredient-story potential for ad copy. High repeat-purchase rate once customers see results.', 'https://images.unsplash.com/photo-1631310709791-1b3701c7a335?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 81, 'Trending', true),

-- Fitness & Wellness (6)
('Adjustable Dumbbell Set', 'Space-saving adjustable dumbbells that replace an entire rack — a top home-gym SKU as the at-home fitness trend holds steady. Higher AOV and strong upsell potential with resistance bands.', 'https://images.unsplash.com/photo-1703668984128-b506579acdd2?w=400', 'Fitness & Wellness', 'https://www.aliexpress.com', 92, 'Hot', true),
('Percussion Massage Gun', 'Deep-tissue massage gun that crossed over from athletes to mainstream recovery routines — one of the highest-converting fitness-recovery SKUs of the last two years. Strong repeat gifting potential.', 'https://images.unsplash.com/photo-1746278925416-9d6c71f55c2d?w=400', 'Fitness & Wellness', 'https://www.aliexpress.com', 94, 'Hot', true),
('Balance & Stretch Yoga Wheel', 'Back-stretching yoga wheel with a dedicated, highly engaged niche audience on yoga and mobility content. Compact shipping profile with a loyal repeat-customer base.', 'https://images.unsplash.com/photo-1774437668830-ea126e751f74?w=400', 'Fitness & Wellness', 'https://www.aliexpress.com', 77, 'Rising', true),
('Compression Foot Massager', 'Shiatsu compression foot massager targeting the "long shift" and "on your feet all day" pain-point audience — a strong, specific ad angle. Higher price point supports healthy margins.', 'https://images.unsplash.com/photo-1706795033796-0057e5864e6d?w=400', 'Fitness & Wellness', 'https://www.aliexpress.com', 83, 'Trending', true),
('Balance Board Trainer', 'Wobble balance board used for core training and rehab, appealing to both fitness enthusiasts and physical-therapy audiences. Simple, durable product with strong evergreen demand.', 'https://images.unsplash.com/photo-1541757088-906d4dcd1a0f?w=400', 'Fitness & Wellness', 'https://www.aliexpress.com', 72, 'Rising', true),
('Adjustable Weighted Vest', 'Adjustable-weight vest for walking, running, and strength training — riding the "rucking" fitness trend that''s exploded across YouTube and TikTok fitness content. Strong AOV with real repeat-purchase upside via added weight plates.', 'https://images.unsplash.com/photo-1637579103895-9ba8218e9aca?w=400', 'Fitness & Wellness', 'https://www.aliexpress.com', 88, 'Hot', true),

-- Tech Accessories (5)
('Foldable Aluminum Laptop Stand', 'Portable laptop stand aimed at the remote-work and coffee-shop-office audience — a reliable evergreen tech accessory with consistent demand. Ships flat and folds for easy travel, a strong ad demo hook.', 'https://images.unsplash.com/photo-1652198145075-b41c363792d3?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 79, 'Trending', true),
('Magnetic Cable Organizer Clips', 'Cheap, tiny magnetic clips that solve a universal desk-clutter problem — extremely high margin with strong add-on/upsell potential at checkout. Frequently featured in "desk setup" content.', 'https://images.unsplash.com/photo-1760348213270-7cd00b8c3405?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 73, 'Rising', true),
('Adjustable Phone Ring Holder Stand', 'Foldable ring stand that doubles as a kickstand — a low-cost, high-volume accessory that performs well as a checkout add-on for any phone-accessory offer.', 'https://images.unsplash.com/photo-1623394088867-503931dff665?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 74, 'Rising', true),
('7-in-1 USB-C Hub Multiport Adapter', 'Multiport hub solving the "no ports left" pain point for modern laptops — a practical, specific offer with strong search intent from remote workers and students.', 'https://images.unsplash.com/photo-1760376789487-994070337c76?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 80, 'Trending', true),
('Ergonomic Wireless Mouse', 'Vertical ergonomic mouse targeting the "wrist pain from WFH" audience — a specific, high-intent pain-point angle that converts well on informational ad creative.', 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 76, 'Rising', true),

-- Baby & Kids (4)
('Montessori Wooden Stacking Toy', 'Open-ended wooden stacking toy aligned with the fast-growing Montessori-parenting content niche. Premium natural-material positioning supports a higher price point and strong gifting demand.', 'https://images.unsplash.com/photo-1641563817292-d2085b953e78?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 78, 'Trending', true),
('Baby Swimming Float Ring', 'Safety-seat swim float for babies and toddlers, with strong seasonal demand spikes heading into summer. High-intent purchase from parents planning pool or beach trips.', 'https://images.unsplash.com/photo-1565495612491-a830ecb85626?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 75, 'Rising', true),
('Kids Anti-Lost Backpack Harness', 'Toddler backpack with a built-in safety harness/leash — a strong pain-point angle for parents navigating crowded places. Cute animal designs drive impulse add-to-cart from gift shoppers too.', 'https://images.unsplash.com/photo-1722963126401-f9c9f7b4ea6e?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 77, 'Rising', true),
('Silicone Teething Necklace', 'Food-grade silicone teething necklace worn by parents rather than baby, tapping into the "mom hack" content niche. Simple, safe, and cheap to ship with strong repeat-gifting potential at baby showers.', 'https://images.unsplash.com/photo-1627251597138-7c5f1e5b8719?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 73, 'Rising', true),

-- Car Accessories (4)
('Multi-Pocket Car Trunk Organizer', 'Collapsible trunk organizer that solves a universal car-clutter problem — practical, high-intent purchase with broad appeal across every vehicle owner. Strong "car hacks" video potential.', 'https://images.unsplash.com/photo-1768671496923-e43c94b5f60f?w=400', 'Car Accessories', 'https://www.aliexpress.com', 76, 'Rising', true),
('Foldable Windshield Sun Shade', 'Reflective foldable sun shade with strong seasonal demand every spring and summer. Extremely cheap to ship and a near-universal fit, keeping return rates low.', 'https://images.unsplash.com/photo-1599803625569-f9f93ff46d40?w=400', 'Car Accessories', 'https://www.aliexpress.com', 72, 'Rising', true),
('Handheld Cordless Car Vacuum', 'Compact cordless vacuum sized specifically for car interiors — a strong "clean car" before/after ad angle with genuinely useful everyday function. Higher AOV than most car-accessory SKUs.', 'https://images.unsplash.com/photo-1746645297698-306ef29852ca?w=400', 'Car Accessories', 'https://www.aliexpress.com', 84, 'Trending', true),
('Car Seat Gap Filler Organizer', 'Wedge-shaped organizer that plugs the gap between car seats — a small, cheap, satisfying "problem solved" product that performs extremely well in short-form demo ads.', 'https://images.unsplash.com/photo-1613191683446-be5b22d4fff7?w=400', 'Car Accessories', 'https://www.aliexpress.com', 73, 'Rising', true),

-- Outdoor & Garden (4)
('Solar Powered Garden Path Lights Set', 'No-wiring solar path lights that install in minutes — a strong "instant curb appeal" ad angle heading into spring and summer. Sold as a multi-pack for higher AOV.', 'https://images.unsplash.com/photo-1774265537519-05c29a22bc32?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 79, 'Trending', true),
('Self-Watering Plant Pot', 'Reservoir-base pot that waters plants automatically for up to two weeks — a strong pain-point angle for the "I keep killing my plants" audience. Broad appeal across the huge houseplant niche.', 'https://images.unsplash.com/photo-1702568227996-0d39769fd2ab?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 81, 'Trending', true),
('Retractable Expandable Garden Hose', 'Expandable hose that triples in length under water pressure then shrinks back for easy storage — a proven, recurring "as seen on TV" style bestseller every spring.', 'https://images.unsplash.com/photo-1715407157720-aff745f27568?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 74, 'Rising', true),
('Outdoor Patio String Lights', 'Weatherproof string lights that anchor the "backyard oasis" content trend across Pinterest and Instagram. Strong seasonal spike with high repeat-purchase rate for multi-strand setups.', 'https://images.unsplash.com/photo-1773089155567-cdb5c15c6a9c?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 86, 'Trending', true);
