-- Batch 3: 70 additional winning dropshipping products, bringing the
-- catalog to 150. Every image_url was chosen from a live Unsplash search
-- for that specific product, verified to return HTTP 200 / image/jpeg,
-- and cross-checked against batch 1 and batch 2 to avoid any repeats.

INSERT INTO products (title, description, image_url, niche, supplier_url, demand_score, trend_label, is_featured) VALUES

-- Home Decor (10)
('Personalized LED Name Neon Sign', 'Custom LED neon sign spelling any name or word, a staple "room reveal" product across TikTok and Instagram home content. High perceived value with a strong built-in upsell via personalization.', 'https://images.unsplash.com/photo-1661298889141-14da83db9821?w=400', 'Home Decor', 'https://www.aliexpress.com', 87, 'Trending', true),
('Floating Wood Wall Shelves Set', 'Set of minimalist floating shelves for books, plants, and decor — a recurring feature in small-space and apartment-makeover content. Easy install angle makes for strong short-form demo videos.', 'https://images.unsplash.com/photo-1641644785936-fc6e54131f14?w=400', 'Home Decor', 'https://www.aliexpress.com', 76, 'Rising', true),
('Minimalist Wall Clock', 'Silent-sweep minimalist wall clock that fits any decor style — a low-cost, broad-appeal SKU with consistent year-round demand. Strong gifting angle for housewarmings.', 'https://images.unsplash.com/photo-1633603125151-6a3c1a4778a5?w=400', 'Home Decor', 'https://www.aliexpress.com', 72, 'Rising', true),
('Macrame Plant Hanger', 'Handwoven macrame hanger for displaying potted plants — rides the sustained plant-parent and boho-decor trend. Cheap to ship, high margin, and a favorite in "cozy corner" Pinterest content.', 'https://images.unsplash.com/photo-1746450912857-60bdc3b5d8df?w=400', 'Home Decor', 'https://www.aliexpress.com', 78, 'Trending', true),
('Boho Tapestry Wall Hanging', 'Large fabric tapestry that instantly transforms a bare wall — one of the highest ad-to-purchase converting dorm and first-apartment SKUs. Ships flat for excellent margins.', 'https://images.unsplash.com/photo-1572466667933-375a15e24171?w=400', 'Home Decor', 'https://www.aliexpress.com', 80, 'Trending', true),
('Geometric Metal Wall Art', 'Modern geometric metal wall art piece that elevates a living room without needing a large budget — strong "before and after" ad angle. Broad appeal across minimalist and industrial decor styles.', 'https://images.unsplash.com/photo-1760030427734-076184daf040?w=400', 'Home Decor', 'https://www.aliexpress.com', 74, 'Rising', true),
('LED Strip Lights for Room', 'App-controlled RGB LED strip lighting for bedrooms and gaming setups — one of the most consistently viral "room transformation" categories on TikTok. Strong upsell potential with longer strips and accessories.', 'https://images.unsplash.com/photo-1565382038303-8c62e88d119a?w=400', 'Home Decor', 'https://www.aliexpress.com', 91, 'Hot', true),
('Woven Rattan Pendant Light', 'Handwoven rattan pendant light fixture that anchors the "boho kitchen" and "coastal home" aesthetics trending in decor content. Higher AOV than most lighting SKUs with strong visual impact.', 'https://images.unsplash.com/photo-1643509877015-c90830bb8519?w=400', 'Home Decor', 'https://www.aliexpress.com', 77, 'Rising', true),
('Ceramic Vase Set', 'Matching set of minimalist ceramic vases sold as a bundle — a proven "shelf styling" product with strong repeat interest across decor styles. Low shipping weight relative to visual impact.', 'https://images.unsplash.com/photo-1631125915902-d8abe9225ff2?w=400', 'Home Decor', 'https://www.aliexpress.com', 73, 'Rising', true),
('Faux Fur Area Rug', 'Plush faux fur accent rug that adds instant coziness to a bedroom or living room corner — a strong "cozy aesthetic" ad angle with high perceived value. Popular gifting item during the winter season.', 'https://images.unsplash.com/photo-1538476336763-16a34df6f3de?w=400', 'Home Decor', 'https://www.aliexpress.com', 79, 'Trending', true),

-- Kitchen Gadgets (10)
('Electric Egg Cooker', 'Countertop electric egg cooker that boils, poaches, or steams eggs perfectly every time — a reliable "kitchen hack" video subject with genuinely useful daily function. Strong repeat-purchase base among meal-preppers.', 'https://images.unsplash.com/photo-1680987398307-e1ae27a6ed67?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 75, 'Rising', true),
('Vegetable Spiralizer', 'Handheld vegetable spiralizer for zucchini noodles and low-carb meal prep — rides the sustained healthy-eating content wave. Compact, cheap to ship, and easy to demo in a 15-second video.', 'https://images.unsplash.com/photo-1524240293321-31b1b9a207af?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 78, 'Trending', true),
('Multi-Function Breakfast Sandwich Maker', 'Compact appliance that cooks a full breakfast sandwich (egg, meat, cheese, bread) in one shot — a strong "morning routine" viral category with broad audience appeal.', 'https://images.unsplash.com/photo-1643473806845-485d1f11688c?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 83, 'Trending', true),
('Automatic Pan Stirrer', 'Battery-powered automatic stirrer that keeps sauces and soups moving hands-free — a novelty "set it and forget it" product with strong impulse-buy appeal and satisfying demo footage.', 'https://images.unsplash.com/photo-1679745208379-dbf9d01699f4?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 71, 'Rising', true),
('Electric Can Opener', 'One-touch electric can opener aimed at the accessibility and convenience-focused kitchen-gadget audience — evergreen demand with a genuinely useful, specific pain-point angle.', 'https://images.unsplash.com/photo-1687553644341-a8569c9e52f7?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 72, 'Rising', true),
('Salad Chopper Bowl', 'All-in-one chopping bowl that dices a full salad in seconds with a rocking blade — a strong "healthy meal prep" ad angle with satisfying demo potential.', 'https://images.unsplash.com/photo-1688228499386-4a90778f8152?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 80, 'Trending', true),
('Reusable Coffee Filter Pods', 'Refillable coffee pods compatible with single-serve machines — strong eco-angle messaging paired with real cost savings, a proven combination for conversion. Sold as a multi-pack for higher AOV.', 'https://images.unsplash.com/photo-1649897657363-821f6de60e1e?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 76, 'Rising', true),
('Digital Kitchen Scale', 'Precision digital kitchen scale for baking and portion control — a reliable evergreen SKU with consistent demand from the meal-prep and baking niches. Compact and cheap to ship.', 'https://images.unsplash.com/photo-1753091122032-ddfb454849cc?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 74, 'Rising', true),
('Bacon Cooker Microwave Rack', 'Microwave-safe bacon rack that cooks crispy bacon in minutes without the mess of a stovetop — a satisfying, specific "kitchen hack" with strong short-form video appeal.', 'https://images.unsplash.com/photo-1779649577828-a0dc5f7bb095?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 73, 'Rising', true),
('Onion Chopper Goggles', 'Novelty goggles that seal out onion fumes to stop eye-watering while chopping — a genuinely funny, highly shareable "as seen on TikTok" product with strong organic reach potential.', 'https://images.unsplash.com/photo-1690944250252-71a40fa6fccf?w=400', 'Kitchen Gadgets', 'https://www.aliexpress.com', 77, 'Rising', true),

-- Pet Supplies (8)
('Cat Tunnel Toy', 'Collapsible play tunnel that taps into cats'' natural hiding and pouncing instincts — one of the most reliably engaging cat-toy categories with strong repeat-purchase potential across multiple colors.', 'https://images.unsplash.com/photo-1742565850085-bf02c1e7cba4?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 79, 'Trending', true),
('Dog Cooling Mat', 'Pressure-activated cooling gel mat that keeps dogs comfortable in warm weather — strong seasonal spike every spring and summer with a clear, specific pain-point angle.', 'https://images.unsplash.com/photo-1750087327530-8fe2f73b015e?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 76, 'Rising', true),
('Automatic Pet Feeder with Camera', 'WiFi pet feeder with a built-in camera for scheduled feeding and remote monitoring — a premium SKU that taps into the growing "working pet owner" audience. Higher AOV with strong perceived value.', 'https://images.unsplash.com/photo-1775387307543-4411d4b4863d?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 90, 'Hot', true),
('Pet Camera Treat Dispenser', 'Two-way camera and treat dispenser that lets owners check in and reward pets remotely — a strong "working from home guilt" ad angle with premium positioning and high AOV.', 'https://images.unsplash.com/photo-1741061962757-3a96e9dbc9e8?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 85, 'Trending', true),
('Cat Window Perch', 'Suction-mounted window perch that gives cats a sunny spot to watch the world — a simple, satisfying product with strong "cat content" organic reach potential.', 'https://images.unsplash.com/photo-1762652847612-25cc2ad1705c?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 75, 'Rising', true),
('Dog Life Jacket', 'High-visibility flotation vest for dogs on boats or at the beach — strong seasonal demand with a genuine safety angle that resonates with active dog owners.', 'https://images.unsplash.com/photo-1718813462719-2591adc73083?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 73, 'Rising', true),
('Pet Nail Grinder', 'Quiet, low-vibration nail grinder that makes an anxiety-inducing task easier for pets and owners alike — a strong "before and after" content angle with genuine daily-use utility.', 'https://images.unsplash.com/photo-1735463358600-b62899139262?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 74, 'Rising', true),
('Slow Feeder Dog Bowl', 'Maze-pattern bowl that slows down fast eaters to improve digestion — a vet-recommended upgrade with a clear, specific pain-point angle and broad appeal across breeds.', 'https://images.unsplash.com/photo-1678783133022-89e103910f76?w=400', 'Pet Supplies', 'https://www.aliexpress.com', 78, 'Trending', true),

-- Beauty & Skincare (8)
('Blackhead Pore Vacuum', 'Suction-based pore cleansing device that''s a reliable "satisfying extraction" content category — strong organic reach potential paired with genuine skincare-routine utility.', 'https://images.unsplash.com/photo-1761718209794-e0588aafbcc4?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 84, 'Trending', true),
('Eyebrow Shaping Trimmer', 'Precision trimmer for at-home eyebrow shaping — a low-cost, high-frequency-use beauty tool with strong tutorial-driven organic reach on short-form video.', 'https://images.unsplash.com/photo-1783013951101-2d9ed3eac234?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 76, 'Rising', true),
('Lip Plumping Device', 'Suction-based lip plumping tool marketed as a filler alternative — a proven viral beauty category with strong before/after UGC potential and impulse-buy pricing.', 'https://images.unsplash.com/photo-1512351660358-6bed42b7b842?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 81, 'Trending', true),
('Cryo Facial Ice Roller Set', 'Two-piece cryo roller set for depuffing and skin tightening — a low-cost, high-margin "morning routine" staple with consistent demand across the skincare niche.', 'https://images.unsplash.com/photo-1542837412-fcdcd08c9aad?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 79, 'Trending', true),
('Derma Roller Microneedle Set', 'At-home microneedling set targeting fine lines and product absorption — a strong ingredient-story ad angle for the skincare-enthusiast audience with high repeat-purchase potential.', 'https://images.unsplash.com/photo-1747818161434-d16efd87d44d?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 82, 'Trending', true),
('LED Light Therapy Wand', 'Handheld LED light therapy wand targeting acne and fine lines — rides the at-home skincare-device trend with strong before/after content potential and premium positioning.', 'https://images.unsplash.com/photo-1754941622117-97957c5d669b?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 88, 'Hot', true),
('Nail Polish Dryer Lamp', 'Compact UV/LED lamp for curing gel nail polish at home — taps into the huge at-home manicure trend with strong repeat-purchase economics once a customer buys gel polish too.', 'https://images.unsplash.com/photo-1602585578130-c9076e09330d?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 77, 'Rising', true),
('Hair Removal Device', 'Painless electric hair removal device marketed as a razor alternative — a proven evergreen beauty category with broad appeal and strong repeat-purchase potential for replacement heads.', 'https://images.unsplash.com/photo-1535980970317-d11b81e869ee?w=400', 'Beauty & Skincare', 'https://www.aliexpress.com', 86, 'Trending', true),

-- Fitness (8)
('Ab Roller Wheel', 'Simple, effective core-training wheel that''s a staple in home-gym starter kits — extremely low cost of goods with strong margin and broad evergreen appeal.', 'https://images.unsplash.com/photo-1571019613576-2b22c76fd955?w=400', 'Fitness', 'https://www.aliexpress.com', 74, 'Rising', true),
('Smart Jump Rope with Counter', 'Digital jump rope that counts reps and calories via a built-in display — a strong "home cardio" ad angle riding the at-home fitness trend with genuine daily-use utility.', 'https://images.unsplash.com/photo-1514994667787-b48ca37155f0?w=400', 'Fitness', 'https://www.aliexpress.com', 80, 'Trending', true),
('Fabric Resistance Loop Bands Set', 'Non-slip fabric resistance bands for glute and leg workouts — a top-performing home-fitness category with strong repeat interest from the growing "booty workout" content niche.', 'https://images.unsplash.com/photo-1601838165307-6a5a08616f97?w=400', 'Fitness', 'https://www.aliexpress.com', 83, 'Trending', true),
('Mini Massage Gun', 'Compact, travel-sized percussion massager for on-the-go recovery — a lower-priced entry point into the massage-gun category with strong gifting appeal.', 'https://images.unsplash.com/photo-1767043088777-1884c2ef6c97?w=400', 'Fitness', 'https://www.aliexpress.com', 85, 'Trending', true),
('Pull Up Bar Doorway', 'No-screw doorway pull-up bar that turns any home into a functional gym corner — a reliable evergreen SKU with strong appeal across the calisthenics and home-fitness niches.', 'https://images.unsplash.com/photo-1519506098321-977c3a106928?w=400', 'Fitness', 'https://www.aliexpress.com', 76, 'Rising', true),
('Grip Strengthener Set', 'Adjustable hand grip trainers sold as a set of varying resistance — a low-cost, high-margin accessory with strong appeal to climbers, lifters, and rehab audiences alike.', 'https://images.unsplash.com/photo-1556232503-2c7aca160281?w=400', 'Fitness', 'https://www.aliexpress.com', 71, 'Rising', true),
('Foam Roller', 'High-density foam roller for muscle recovery and myofascial release — an evergreen fitness-recovery staple with consistent demand from both athletes and casual gym-goers.', 'https://images.unsplash.com/photo-1653617748437-895c016e88b1?w=400', 'Fitness', 'https://www.aliexpress.com', 75, 'Rising', true),
('Ankle Resistance Bands', 'Adjustable ankle straps for cable-style leg workouts at home — a specific, high-intent purchase from the growing glute-training content niche with strong repeat-purchase potential.', 'https://images.unsplash.com/photo-1565122744328-de4388588c1f?w=400', 'Fitness', 'https://www.aliexpress.com', 72, 'Rising', true),

-- Tech Accessories (8)
('Magnetic Phone Case', 'MagSafe-compatible phone case that snaps onto mounts, wallets, and chargers — rides the growing magnetic-accessory ecosystem with strong cross-sell potential to mounts and wallets.', 'https://images.unsplash.com/photo-1581003989504-3e6ba26df4a2?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 81, 'Trending', true),
('Screen Cleaner Kit', 'All-in-one microfiber cleaning kit for phones, laptops, and monitors — a low-cost, high-margin accessory that performs well as a checkout add-on across any tech offer.', 'https://images.unsplash.com/photo-1692645214212-ea7fdb37ca6d?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 70, 'Rising', true),
('Cable Management Box', 'Enclosed box that hides power strips and cable clutter under a desk — a strong "clean desk setup" ad angle with genuinely useful everyday function.', 'https://images.unsplash.com/photo-1575729853562-e3ad7084c28d?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 73, 'Rising', true),
('Webcam Cover Slide', 'Ultra-thin sliding webcam cover addressing privacy concerns — an inexpensive, high-margin accessory with broad appeal across the remote-work and privacy-conscious audience.', 'https://images.unsplash.com/photo-1629429407756-446d66f5b24e?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 69, 'Rising', true),
('Phone Camera Lens Kit', 'Clip-on wide-angle and macro lens set for smartphone photography — a strong "content creator" ad angle with broad appeal across the growing creator-economy audience.', 'https://images.unsplash.com/photo-1511680059018-e7cc6c0f22c8?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 78, 'Trending', true),
('Portable Power Bank', 'Slim, high-capacity power bank for travel and everyday carry — an evergreen tech accessory with consistent demand and strong cross-sell potential with cables and cases.', 'https://images.unsplash.com/photo-1566554738544-d962991c3fee?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 82, 'Trending', true),
('Mini GPS Item Finder', 'Coin-sized Bluetooth tracker for keys, bags, and wallets — evergreen demand with a strong repeat-purchase rate as customers buy multiples for different items.', 'https://images.unsplash.com/photo-1754821305530-8e3c7b8deda2?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 79, 'Trending', true),
('Laptop Sleeve Case', 'Padded, water-resistant laptop sleeve with a minimalist design — a reliable evergreen accessory with broad appeal across students, remote workers, and commuters.', 'https://images.unsplash.com/photo-1763034179057-acad3a072568?w=400', 'Tech Accessories', 'https://www.aliexpress.com', 72, 'Rising', true),

-- Baby & Kids (6)
('White Noise Sound Machine', 'Portable sound machine with white noise, lullabies, and a night light — a top-selling new-parent SKU with strong gifting demand and consistent evergreen search volume.', 'https://images.unsplash.com/photo-1770407780059-be1a0b3059c6?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 83, 'Trending', true),
('Video Baby Monitor', 'WiFi video baby monitor with two-way audio and night vision — a premium SKU with high perceived value and strong search intent from new and expecting parents.', 'https://images.unsplash.com/photo-1496458857386-d2388f1c03e8?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 89, 'Hot', true),
('Silicone Teether Toys Set', 'BPA-free silicone teething toy set in fun shapes — a safe, giftable staple for the baby-shower and new-parent audience with strong repeat-gifting potential.', 'https://images.unsplash.com/photo-1684577753340-de97c66fa6fd?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 74, 'Rising', true),
('Bath Toy Organizer', 'Mesh bath toy organizer that mounts to the tub wall and drains water to prevent mold — a practical "parent hack" product with a clear, specific pain-point angle.', 'https://images.unsplash.com/photo-1652441547536-f6edb2fc5206?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 71, 'Rising', true),
('Baby Bottle Warmer', 'Fast, even bottle and food warmer designed for nighttime feeds — a practical, high-intent purchase for new parents with strong evergreen demand tied to birth rates.', 'https://images.unsplash.com/photo-1623707430616-d9f956bcac2b?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 77, 'Rising', true),
('Kids Night Light Projector', 'Star and constellation projector that makes bedtime easier — a strong "peaceful bedtime routine" ad angle with broad appeal and high gifting potential.', 'https://images.unsplash.com/photo-1755414718613-3d45827fb9eb?w=400', 'Baby & Kids', 'https://www.aliexpress.com', 80, 'Trending', true),

-- Car Accessories (6)
('Console Side Pocket Organizer', 'Slim organizer that fills the gap beside a car seat to catch phones and loose items — a small, cheap, satisfying "problem solved" product with strong short-form demo appeal.', 'https://images.unsplash.com/photo-1654168552304-2dce2d8d58ef?w=400', 'Car Accessories', 'https://www.aliexpress.com', 72, 'Rising', true),
('Collapsible Trunk Storage Box', 'Foldable trunk organizer that collapses flat when not in use — practical, high-intent purchase with broad appeal and easy "before and after" demo content.', 'https://images.unsplash.com/photo-1759477444242-46d92681a8e1?w=400', 'Car Accessories', 'https://www.aliexpress.com', 75, 'Rising', true),
('Magnetic Car Phone Mount', 'Dashboard-mounted magnetic phone holder for hands-free navigation — an evergreen car-accessory SKU with strong cross-sell potential to magnetic phone cases.', 'https://images.unsplash.com/photo-1708766896345-fe51d8845ae3?w=400', 'Car Accessories', 'https://www.aliexpress.com', 78, 'Trending', true),
('LED Interior Car Lights', 'App-controlled RGB interior car lighting kit — a strong "car mod" viral category on TikTok with broad appeal across the car-enthusiast and youth audience.', 'https://images.unsplash.com/photo-1615135902020-f499dc74b655?w=400', 'Car Accessories', 'https://www.aliexpress.com', 84, 'Trending', true),
('Car Dashboard Camera', 'Compact dash cam with loop recording and night vision — a growing safety-driven category with strong search intent from rideshare drivers and everyday commuters.', 'https://images.unsplash.com/photo-1643686978040-beac9782e58b?w=400', 'Car Accessories', 'https://www.aliexpress.com', 86, 'Trending', true),
('Steering Wheel Cover', 'Ergonomic, non-slip steering wheel cover with a premium leather-look finish — a low-cost, high-margin accessory with broad universal-fit appeal.', 'https://images.unsplash.com/photo-1681857239369-15ebd70bdad9?w=400', 'Car Accessories', 'https://www.aliexpress.com', 70, 'Rising', true),

-- Outdoor & Garden (6)
('Solar Powered Fence Lights Set', 'No-wiring solar lights that clip onto fences and railings — a strong "instant curb appeal" ad angle heading into spring, sold as a multi-pack for higher AOV.', 'https://images.unsplash.com/photo-1643214065824-824f21ca6cb2?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 76, 'Rising', true),
('Collapsible Watering Can', 'Space-saving watering can that folds flat for storage — a practical "small space gardening" product with broad appeal across the growing plant-parent audience.', 'https://images.unsplash.com/photo-1692651771569-95dd3ed878a8?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 71, 'Rising', true),
('Bird Feeder Squirrel Proof', 'Weight-activated bird feeder that closes off access to squirrels — a strong, specific pain-point angle for the backyard-birding hobbyist audience with high repeat-purchase loyalty.', 'https://images.unsplash.com/photo-1598280860721-14d1fd80a8af?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 78, 'Trending', true),
('Garden Kneeler Seat', 'Foldable garden kneeler that converts to a seat, with side pockets for tools — a practical gifting product for the gardening hobbyist audience with a clear comfort-driven angle.', 'https://images.unsplash.com/photo-1621272156506-cdbdb6a47243?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 73, 'Rising', true),
('Outdoor Solar Fountain', 'Solar-powered tabletop fountain for patios and gardens — a strong "backyard oasis" ad angle with premium positioning and no wiring required, driving high conversion on demo video.', 'https://images.unsplash.com/photo-1623275563401-6f9c556355a8?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 79, 'Trending', true),
('Hammock Camping Chair', 'Portable, lightweight camping hammock that packs into its own stuff sack — rides the sustained outdoor-recreation and camping-gear trend with strong seasonal demand.', 'https://images.unsplash.com/photo-1602174207566-41fce5d08e0b?w=400', 'Outdoor & Garden', 'https://www.aliexpress.com', 82, 'Trending', true);
