-- Fall 2026 launch waitlist. Signups are anonymous (no auth required), so
-- this table is locked down to service-role access only — all reads/writes
-- go through /api/waitlist/* and /api/admin/waitlist, never direct
-- client-side Supabase calls. RLS is enabled with no policies granted to
-- anon/authenticated, so it's deny-by-default for those roles.

CREATE TABLE IF NOT EXISTS waitlist_subscribers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  name text,
  referral_code text UNIQUE,
  -- Referral code of whoever referred this signup, if any. Not a foreign
  -- key on purpose: codes come in via a public ?ref= URL param, and a
  -- stale/invalid code should just be ignored (looked up and validated in
  -- the API route) rather than fail the whole signup with a FK violation.
  referred_by text,
  source text,
  created_at timestamptz NOT NULL DEFAULT now(),
  notified boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_waitlist_subscribers_referred_by ON waitlist_subscribers (referred_by);
CREATE INDEX IF NOT EXISTS idx_waitlist_subscribers_created_at ON waitlist_subscribers (created_at);

ALTER TABLE waitlist_subscribers ENABLE ROW LEVEL SECURITY;
-- No policies for anon/authenticated — intentionally unreachable from the
-- client. The service-role client (used server-side only) bypasses RLS.

-- Every subscriber gets a unique 8-char referral code, generated by the DB
-- so uniqueness is guaranteed without a client-side collision-retry loop —
-- same pattern as profiles.referral_code in referral_migration.sql.
CREATE OR REPLACE FUNCTION generate_unique_waitlist_referral_code()
RETURNS text AS $$
DECLARE
  new_code text;
  code_exists boolean;
BEGIN
  LOOP
    new_code := upper(substring(md5(random()::text || clock_timestamp()::text) from 1 for 8));
    SELECT EXISTS(SELECT 1 FROM waitlist_subscribers WHERE referral_code = new_code) INTO code_exists;
    EXIT WHEN NOT code_exists;
  END LOOP;
  RETURN new_code;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_waitlist_referral_code()
RETURNS trigger AS $$
BEGIN
  IF NEW.referral_code IS NULL THEN
    NEW.referral_code := generate_unique_waitlist_referral_code();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_waitlist_referral_code ON waitlist_subscribers;
CREATE TRIGGER trg_set_waitlist_referral_code
BEFORE INSERT ON waitlist_subscribers
FOR EACH ROW
EXECUTE FUNCTION set_waitlist_referral_code();
