'use client'

import { useState } from 'react'
import Image from 'next/image'
import {
  TrendingUp, TrendingDown, Minus, Users, Tag, Megaphone, Calendar,
  Lightbulb, Target, DollarSign, Clipboard, Check, Sparkles,
} from 'lucide-react'

export type ScrapedProduct = { title: string; price: string; image_url: string }

export type StoreAnalysis = {
  store_name: string
  estimated_monthly_revenue: string
  estimated_monthly_visitors: string
  confidence_level: 'Low' | 'Medium' | 'High'
  top_products: ScrapedProduct[]
  main_niches: string[]
  ad_activity: 'Active' | 'Low' | 'Unknown'
  store_age_estimate: string
  revenue_trend: 'Growing' | 'Stable' | 'Declining' | 'Unknown'
  insights: string[]
  winning_angles: string[]
}

const confidenceStyles: Record<string, { badge: string; bar: string; track: string; label: string }> = {
  Low: { badge: 'bg-gray-800 text-gray-400 border-gray-700', bar: 'bg-gray-500', track: 'bg-gray-800', label: 'text-gray-400' },
  Medium: { badge: 'bg-yellow-500/15 text-yellow-400 border-yellow-500/30', bar: 'bg-yellow-500', track: 'bg-yellow-950/50', label: 'text-yellow-400' },
  High: { badge: 'bg-emerald-600/15 text-emerald-400 border-emerald-500/30', bar: 'bg-emerald-500', track: 'bg-emerald-950/50', label: 'text-emerald-400' },
}

const confidenceWidth: Record<string, string> = { Low: '33%', Medium: '66%', High: '100%' }

const trendConfig: Record<string, { icon: typeof TrendingUp; color: string }> = {
  Growing: { icon: TrendingUp, color: 'text-emerald-400' },
  Stable: { icon: Minus, color: 'text-gray-400' },
  Declining: { icon: TrendingDown, color: 'text-red-400' },
  Unknown: { icon: Minus, color: 'text-gray-500' },
}

function buildReportText(analysis: StoreAnalysis, storeUrl?: string) {
  const lines = [
    `Store Intelligence Report — ${analysis.store_name}`,
    storeUrl ?? '',
    '',
    `Estimated Monthly Revenue: ${analysis.estimated_monthly_revenue} (${analysis.confidence_level} confidence)`,
    `Estimated Monthly Visitors: ${analysis.estimated_monthly_visitors}`,
    `Revenue Trend: ${analysis.revenue_trend}`,
    `Main Niches: ${analysis.main_niches?.join(', ') || 'Unknown'}`,
    `Ad Activity: ${analysis.ad_activity}`,
    `Store Age: ${analysis.store_age_estimate}`,
    '',
    'Top Products:',
    ...(analysis.top_products ?? []).map((p) => `- ${p.title} (${p.price})`),
    '',
    'AI Insights:',
    ...(analysis.insights ?? []).map((insight, i) => `${i + 1}. ${insight}`),
    '',
    'Winning Angles:',
    ...(analysis.winning_angles ?? []).map((angle) => `- ${angle}`),
    '',
    'Generated by Launchory Store Intelligence — launchory.io',
  ]
  return lines.join('\n')
}

export function StoreAnalysisCard({
  analysis,
  storeUrl,
  isDemo,
}: {
  analysis: StoreAnalysis
  storeUrl?: string
  isDemo?: boolean
}) {
  const [copied, setCopied] = useState(false)
  const confidence = confidenceStyles[analysis.confidence_level] ?? confidenceStyles.Low
  const trend = trendConfig[analysis.revenue_trend] ?? trendConfig.Unknown
  const TrendIcon = trend.icon

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(buildReportText(analysis, storeUrl))
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Clipboard API unavailable — nothing actionable to do here.
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-3 flex-wrap">
        {isDemo ? (
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-indigo-600/15 border border-indigo-500/30 text-indigo-300 text-xs font-semibold">
            <Sparkles size={12} />
            Example report — see what you&rsquo;ll get
          </div>
        ) : <div />}
        <button
          onClick={handleCopy}
          className="inline-flex items-center gap-2 bg-gray-900 hover:bg-gray-800 border border-gray-800 hover:border-gray-600 text-gray-300 text-xs font-semibold px-3.5 py-2 rounded-lg transition-colors"
        >
          {copied ? <Check size={13} className="text-emerald-400" /> : <Clipboard size={13} />}
          {copied ? 'Copied!' : 'Copy Report'}
        </button>
      </div>

      {/* Revenue card */}
      <div className="bg-gradient-to-br from-indigo-600/15 to-gray-900 border border-indigo-500/20 rounded-2xl p-6 sm:p-8">
        <div className="flex items-center justify-between gap-4 mb-4 flex-wrap">
          <h2 className="text-white font-bold text-lg">{analysis.store_name}</h2>
          <span className={`px-2.5 py-1 rounded-full text-xs font-semibold border ${confidence.badge}`}>
            {analysis.confidence_level} Confidence
          </span>
        </div>
        <div className="flex items-center gap-2 mb-1">
          <DollarSign size={26} className="text-emerald-400 shrink-0" />
          <span className="text-4xl sm:text-5xl font-bold text-white tracking-tight">{analysis.estimated_monthly_revenue}</span>
        </div>
        <p className="text-gray-500 text-sm mb-4">Estimated monthly revenue</p>
        <div className={`h-2 w-full rounded-full overflow-hidden ${confidence.track}`}>
          <div
            className={`h-full rounded-full ${confidence.bar} transition-all duration-500`}
            style={{ width: confidenceWidth[analysis.confidence_level] ?? confidenceWidth.Low }}
          />
        </div>
        <p className={`text-xs mt-1.5 font-medium ${confidence.label}`}>
          {analysis.confidence_level} confidence estimate — based on scraped storefront data
        </p>
        <p className="text-gray-600 text-xs mt-3 leading-relaxed">
          Revenue estimates are approximations based on available public data and AI analysis. Actual figures may vary significantly.
        </p>
      </div>

      {/* Metrics row */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-4">
          <Users size={15} className="text-indigo-400 mb-2" />
          <p className="text-white font-semibold text-sm">{analysis.estimated_monthly_visitors}</p>
          <p className="text-gray-500 text-xs mt-0.5">Monthly visitors</p>
        </div>
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-4">
          <Tag size={15} className="text-indigo-400 mb-2" />
          <p className="text-white font-semibold text-sm truncate">{analysis.main_niches?.join(', ') || 'Unknown'}</p>
          <p className="text-gray-500 text-xs mt-0.5">Niches</p>
        </div>
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-4">
          <Megaphone size={15} className="text-indigo-400 mb-2" />
          <p className="text-white font-semibold text-sm">{analysis.ad_activity}</p>
          <p className="text-gray-500 text-xs mt-0.5">Ad activity</p>
        </div>
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-4">
          <Calendar size={15} className="text-indigo-400 mb-2" />
          <p className="text-white font-semibold text-sm">{analysis.store_age_estimate}</p>
          <p className="text-gray-500 text-xs mt-0.5">Store age</p>
        </div>
      </div>

      {/* Revenue trend */}
      <div className="flex items-center gap-3 bg-gray-900 border border-gray-800 rounded-xl px-4 py-3">
        <TrendIcon size={16} className={trend.color} />
        <span className="text-gray-300 text-sm">Revenue trend: <span className={`font-semibold ${trend.color}`}>{analysis.revenue_trend}</span></span>
      </div>

      {/* Top products */}
      {analysis.top_products?.length > 0 && (
        <div>
          <h3 className="text-white font-semibold text-sm mb-3">Top Products</h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {analysis.top_products.slice(0, 8).map((p, i) => (
              <div key={i} className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden">
                <div className="relative h-24 bg-gray-800">
                  {p.image_url && (
                    <Image src={p.image_url} alt={p.title} fill sizes="200px" className="object-cover" unoptimized />
                  )}
                </div>
                <div className="p-2.5">
                  <p className="text-white text-xs font-medium truncate">{p.title}</p>
                  <p className="text-emerald-400 text-xs font-semibold mt-0.5">{p.price}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Insights */}
      {analysis.insights?.length > 0 && (
        <div>
          <div className="flex items-center gap-2 mb-3">
            <Lightbulb size={15} className="text-yellow-400" />
            <h3 className="text-white font-semibold text-sm">AI Insights</h3>
          </div>
          <div className="space-y-2">
            {analysis.insights.map((insight, i) => (
              <div key={i} className="flex items-start gap-3 p-3.5 bg-gray-900 border border-gray-800 rounded-xl">
                <span className="shrink-0 w-5 h-5 bg-yellow-500/15 text-yellow-400 rounded-md flex items-center justify-center text-xs font-bold border border-yellow-500/30">
                  {i + 1}
                </span>
                <p className="text-gray-300 text-sm leading-relaxed">{insight}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Winning angles */}
      {analysis.winning_angles?.length > 0 && (
        <div>
          <div className="flex items-center gap-2 mb-3">
            <Target size={15} className="text-indigo-400" />
            <h3 className="text-white font-semibold text-sm">Winning Angles</h3>
          </div>
          <div className="space-y-2">
            {analysis.winning_angles.map((angle, i) => (
              <div key={i} className="flex items-start gap-3 p-3.5 bg-gray-800/60 border border-gray-700/60 rounded-xl">
                <Target size={14} className="text-indigo-400 mt-0.5 shrink-0" />
                <p className="text-gray-300 text-sm leading-relaxed">{angle}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
